# Generated by Django 5.1.7 on 2025-03-24 14:30

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_crop_alter_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.CharField(default=activities.models.generate_activity_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
