# Generated by Django 5.1.7 on 2025-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_description_alter_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
