# Generated by Django 5.1.7 on 2025-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('status', models.CharField(choices=[('Planting', 'Planting'), ('Growing', 'Growing'), ('Harvesting', 'Harvesting')], max_length=50)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
    ]
