# Generated by Django 5.1.7 on 2025-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('equipment', 'Equipment')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('usage_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('depleted', 'Depleted')], default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
