# Generated by Django 5.1.7 on 2025-03-24 07:35

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(default=resources.models.generate_unique_id, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('Bags', 'Bags'), ('Kilograms', 'Kilograms'), ('Liters', 'Liters'), ('Tons', 'Tons'), ('Units', 'Units'), ('Other', 'Other')], default='Units', max_length=20)),
                ('resource_type', models.CharField(choices=[('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=20)),
                ('usage_status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Depleted', 'Depleted')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
